### ISSUE TITLE
在线预览无法打开

### ISSUE THREAD

**Issue by mrcaidev** [mrnantang/muyu#4]
可能是服务器down了？有没有考虑过用vercel部署下

**Comment by mrnantang** [comment]
感谢回复！服务器的确挂了，因为有人举报我们不规范，没有写明备案号，以及相关备案信息，应该是触碰到了他们的利益。之所以没有添加是因为我们的服务器也临近到期，并且不打算续费了。就算了吧！只是遗憾的地方在于，我们产品的终点居然没撑到服务器到期（12月15号）。

---原始邮件--
发件人: "Yuwang ***@***.***&gt;
发送时间: 2022年12月1日(周四) 晚上7:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mrnantang/muyu] 在线预览无法打开 (Issue #4)




 
可能是服务器down了？有没有考虑过用vercel部署下

**Comment by mrcaidev** [comment]
用vercel部署的话可以不用备案，流程也比较方便，可以了解下

**Comment by mrnantang** [comment]
Yuwang Cai，你好
上周收到你的邮件后，我去关注了解了一下vercel，觉得这是一个非常棒的提议。
一番学习，操作后，现在电子木鱼又重新上线了。并且也升级为https。
遗憾的是，榜单功能下线了，原因是我们的服务器即将到期。
最后，感谢你对我们的帮助，让电子木鱼重回大众视野。祝您生活愉快！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mrnantang/muyu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 晚上11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mrnantang/muyu] 在线预览无法打开 (Issue #4)





 
用vercel部署的话可以不用备案，流程也比较方便，可以了解下

**Comment by mrcaidev** [comment]
服务器问题的话，有两个办法：

1. 后端也有类似 Vercel 的托管方案

Heroku 是最有名的，但它不久之前要收费了。它的替代品可以在这些地方找到：

- [Open Source Alternatives - Heroku](https://www.opensourcealternative.to/?jb-search=heroku)
- [Free for Devs - BaaS](https://free-for.dev/#/?id=baas)
- [Awesome Self-hosted - Software development](https://github.com/awesome-selfhosted/awesome-selfhosted#software-development)

我粗看了一下，觉得 [Open Faas](https://www.openfaas.com/) 不错，但没有亲自体验过，也许可以试一试。

2. 使用全栈框架

使用像 Next.js / Remix 这样的全栈框架的话，前后端就可以一起托管到 Vercel 上。

3. 使用能在前端使用的数据库 SDK

比如 Firebase, Supabase。我推荐后者，开源、免费、好用。
